### PR TITLE
Keep the list of postal codes for a given city

### PR DESCRIPTION
**Pull request by davidbgk**
Useful for https://github.com/etalab/udata/pull/239

### CODE REVIEW

**Comment by noirbizarre** [comment]
r+

**Comment by MattiSG** [comment]
> r+

?

**Comment by davidbgk** [comment]
@MattiSG https://wiki.mozilla.org/Firefox/Code_Review#What_does_r.2B_mean.3F I can't find a better reference for that.

**Comment by davidbgk** [comment]
http://mozweb.readthedocs.org/en/latest/reference/glossary.html is more complete actually

**Comment by MattiSG** [comment]
Thanks for the ref!

**Pull request merged**
